"""First migration

Revision ID: 3020963224d9
Revises: 
Create Date: 2023-04-11 17:13:01.756185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3020963224d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offensive_play',
    sa.Column('playType', sa.String(), nullable=False),
    sa.Column('playId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('playId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offensive_play')
    # ### end Alembic commands ###
