"""First migration

Revision ID: 3c96880535c8
Revises: 3020963224d9
Create Date: 2023-04-11 17:17:36.671473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c96880535c8'
down_revision = '3020963224d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offensiveplay',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playType', sa.String(), nullable=False),
    sa.Column('playId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'playId')
    )
    op.create_index(op.f('ix_offensiveplay_id'), 'offensiveplay', ['id'], unique=False)
    op.drop_table('offensive_play')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offensive_play',
    sa.Column('playType', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('playId', sa.INTEGER(), server_default=sa.text('nextval(\'"offensive_play_playId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('playId', name='offensive_play_pkey')
    )
    op.drop_index(op.f('ix_offensiveplay_id'), table_name='offensiveplay')
    op.drop_table('offensiveplay')
    # ### end Alembic commands ###
