"""Pass

Revision ID: 430b7fa48e3b
Revises: dd075ee0241c
Create Date: 2023-04-13 00:46:42.778172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430b7fa48e3b'
down_revision = 'dd075ee0241c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offensive_play_result', sa.Column('touchdown', sa.Boolean(), nullable=False))
    op.add_column('offensive_play_result', sa.Column('first_down', sa.Boolean(), nullable=False))
    op.add_column('offensive_play_result', sa.Column('coverage', sa.String(), nullable=True))
    op.add_column('offensive_play_result', sa.Column('blitz', sa.Boolean(), nullable=True))
    op.add_column('offensive_play_result', sa.Column('defensive_personnel', sa.String(), nullable=True))
    op.add_column('offensive_play_result', sa.Column('hash', sa.String(), nullable=True))
    op.add_column('offensive_play_result', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offensive_play_result', 'notes')
    op.drop_column('offensive_play_result', 'hash')
    op.drop_column('offensive_play_result', 'defensive_personnel')
    op.drop_column('offensive_play_result', 'blitz')
    op.drop_column('offensive_play_result', 'coverage')
    op.drop_column('offensive_play_result', 'first_down')
    op.drop_column('offensive_play_result', 'touchdown')
    # ### end Alembic commands ###
