"""Pass

Revision ID: 52c19db68ab2
Revises: d301f5da63c2
Create Date: 2023-04-13 21:44:01.400640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c19db68ab2'
down_revision = 'd301f5da63c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formation', sa.Column('pass_play_ids', sa.UUID(), nullable=True))
    op.add_column('formation', sa.Column('run_play_ids', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'formation', 'pass_play', ['pass_play_ids'], ['formation_id'])
    op.create_foreign_key(None, 'formation', 'run_play', ['run_play_ids'], ['formation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'formation', type_='foreignkey')
    op.drop_constraint(None, 'formation', type_='foreignkey')
    op.drop_column('formation', 'run_play_ids')
    op.drop_column('formation', 'pass_play_ids')
    # ### end Alembic commands ###
