"""second

Revision ID: 68342720f928
Revises: 
Create Date: 2023-04-11 18:48:34.840759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68342720f928'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pass_play',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('play_type', sa.String(), nullable=False),
    sa.Column('pass_play_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pass_play_id'], ['pass_play.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pass_play_id'), 'pass_play', ['id'], unique=False)
    op.create_table('offensive_play',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('play_type', sa.String(), nullable=False),
    sa.Column('pass_play_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pass_play_id'], ['pass_play.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offensive_play_id'), 'offensive_play', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offensive_play_id'), table_name='offensive_play')
    op.drop_table('offensive_play')
    op.drop_index(op.f('ix_pass_play_id'), table_name='pass_play')
    op.drop_table('pass_play')
    # ### end Alembic commands ###
