"""second

Revision ID: 76234781aff7
Revises: 
Create Date: 2023-04-13 00:03:56.910186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76234781aff7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formation_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formation_id'), 'formation', ['id'], unique=False)
    op.create_table('offensive_play',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formation', sa.String(), nullable=False),
    sa.Column('play_name', sa.String(), nullable=False),
    sa.Column('caught', sa.Boolean(), nullable=True),
    sa.Column('yards', sa.Integer(), nullable=True),
    sa.Column('ball_carrier', sa.String(), nullable=True),
    sa.Column('YAC', sa.Integer(), nullable=True),
    sa.Column('down', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offensive_play_id'), 'offensive_play', ['id'], unique=False)
    op.create_table('pass_play',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pass_play_id'), 'pass_play', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pass_play_id'), table_name='pass_play')
    op.drop_table('pass_play')
    op.drop_index(op.f('ix_offensive_play_id'), table_name='offensive_play')
    op.drop_table('offensive_play')
    op.drop_index(op.f('ix_formation_id'), table_name='formation')
    op.drop_table('formation')
    # ### end Alembic commands ###
