"""Pass

Revision ID: 8c3ec3b676b2
Revises: f3bc1c4d2602
Create Date: 2023-04-13 21:51:46.697818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3ec3b676b2'
down_revision = 'f3bc1c4d2602'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('formation_run_play_ids_fkey', 'formation', type_='foreignkey')
    op.drop_constraint('formation_pass_play_ids_fkey', 'formation', type_='foreignkey')
    op.drop_column('formation', 'pass_play_ids')
    op.drop_column('formation', 'run_play_ids')
    op.drop_constraint('pass_play_formation_id_key', 'pass_play', type_='unique')
    op.drop_constraint('run_play_formation_id_key', 'run_play', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('run_play_formation_id_key', 'run_play', ['formation_id'])
    op.create_unique_constraint('pass_play_formation_id_key', 'pass_play', ['formation_id'])
    op.add_column('formation', sa.Column('run_play_ids', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('formation', sa.Column('pass_play_ids', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('formation_pass_play_ids_fkey', 'formation', 'pass_play', ['pass_play_ids'], ['formation_id'])
    op.create_foreign_key('formation_run_play_ids_fkey', 'formation', 'run_play', ['run_play_ids'], ['formation_id'])
    # ### end Alembic commands ###
