"""Pass

Revision ID: d301f5da63c2
Revises: 
Create Date: 2023-04-13 21:43:44.207194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd301f5da63c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formation_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formation_id'), 'formation', ['id'], unique=False)
    op.create_table('pass_play',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formation_id', sa.UUID(), nullable=False),
    sa.Column('play_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formation_id')
    )
    op.create_index(op.f('ix_pass_play_id'), 'pass_play', ['id'], unique=False)
    op.create_table('run_play',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formation_id', sa.UUID(), nullable=False),
    sa.Column('play_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formation_id')
    )
    op.create_index(op.f('ix_run_play_id'), 'run_play', ['id'], unique=False)
    op.create_table('offensive_play_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pass_play_id', sa.UUID(), nullable=True),
    sa.Column('run_play_id', sa.UUID(), nullable=True),
    sa.Column('caught', sa.Boolean(), nullable=True),
    sa.Column('yards', sa.Integer(), nullable=True),
    sa.Column('ball_carrier', sa.String(), nullable=True),
    sa.Column('yac', sa.Integer(), nullable=True),
    sa.Column('down', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('touchdown', sa.Boolean(), nullable=False),
    sa.Column('first_down', sa.Boolean(), nullable=False),
    sa.Column('coverage', sa.String(), nullable=True),
    sa.Column('blitz', sa.Boolean(), nullable=True),
    sa.Column('defensive_personnel', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pass_play_id'], ['pass_play.id'], ),
    sa.ForeignKeyConstraint(['run_play_id'], ['run_play.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offensive_play_result_id'), 'offensive_play_result', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offensive_play_result_id'), table_name='offensive_play_result')
    op.drop_table('offensive_play_result')
    op.drop_index(op.f('ix_run_play_id'), table_name='run_play')
    op.drop_table('run_play')
    op.drop_index(op.f('ix_pass_play_id'), table_name='pass_play')
    op.drop_table('pass_play')
    op.drop_index(op.f('ix_formation_id'), table_name='formation')
    op.drop_table('formation')
    # ### end Alembic commands ###
