"""second

Revision ID: dd075ee0241c
Revises: c15d4e1b0645
Create Date: 2023-04-13 00:23:20.641174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd075ee0241c'
down_revision = 'c15d4e1b0645'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offensive_play_result', sa.Column('yac', sa.Integer(), nullable=True))
    op.drop_column('offensive_play_result', 'YAC')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offensive_play_result', sa.Column('YAC', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('offensive_play_result', 'yac')
    # ### end Alembic commands ###
