"""Pass

Revision ID: f3bc1c4d2602
Revises: 52c19db68ab2
Create Date: 2023-04-13 21:45:59.775274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3bc1c4d2602'
down_revision = '52c19db68ab2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
